[package]
name = "push_front"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "This crate implements push_front for Rust std::string::String"
repository = "https://github.com/AlexSherbinin/push_front"